// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/mail.ts";
import * as $3 from "./routes/imprint.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/privacy.tsx";
import * as $$0 from "./islands/contact.tsx";
import * as $$1 from "./islands/language.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/mail.ts": $2,
    "./routes/imprint.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/privacy.tsx": $5,
  },
  islands: {
    "./islands/contact.tsx": $$0,
    "./islands/language.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
